name: Generate Pac-Man Graph # Nome do workflow

on:
  schedule:
    # Roda a cada 12 horas, por exemplo
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Garanta que "uses:" esteja alinhado corretamente dentro de "steps:"
      - uses: actions/checkout@v4 
      - uses: abozanona/pacman-contribution-graph@v1
        with:
          # Adicione suas configurações aqui se precisar
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Exemplo de configuração adicional:
          # GHOST_ENABLED: true 
